extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_naosei_lights;
extern Lights1 bob_dl_dirt_lights;
extern Lights1 bob_dl_grass_lights;
extern Lights1 bob_dl_poste1_lights;
extern Lights1 bob_dl_poste3_lights;
extern Lights1 bob_dl_linha_lights;
extern u8 bob_dl_rr_textures_05800_rgba16_ci8[];
extern u8 bob_dl_rr_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_bob_textures_09000_rgba16_ci8[];
extern u8 bob_dl_bob_textures_09000_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_wf_textures_05800_rgba16_ci8[];
extern u8 bob_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_bob_textures_03000_rgba16_i8[];
extern u8 bob_dl_hmc_textures_0C000_ia16_ia8[];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_0[103];
extern Gfx bob_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[96];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[118];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[128];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[26];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_4[139];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[162];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_naosei[];
extern Gfx mat_revert_bob_dl_naosei[];
extern Gfx mat_bob_dl_dirt[];
extern Gfx mat_revert_bob_dl_dirt[];
extern Gfx mat_bob_dl_grass[];
extern Gfx mat_revert_bob_dl_grass[];
extern Gfx mat_bob_dl_poste1[];
extern Gfx mat_bob_dl_poste3[];
extern Gfx mat_bob_dl_poste4[];
extern Gfx mat_bob_dl_linha[];
extern Gfx bob_dl_Cylinder_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
