extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_grass_lights;
extern Lights1 wf_dl_dirt_lights;
extern Lights1 wf_dl_wood_lights;
extern Lights1 wf_dl_cobblestone_lights;
extern Lights1 wf_dl_bridge_lights;
extern u8 wf_dl_wf_textures_05800_rgba16_ci8[];
extern u8 wf_dl_wf_textures_05800_rgba16_ci8_pal_rgba16[];
extern u8 wf_dl_bob_textures_09000_rgba16_ci8[];
extern u8 wf_dl_bob_textures_09000_rgba16_ci8_pal_rgba16[];
extern u8 wf_dl_jrb_textures_0A000_rgba16_ci8[];
extern u8 wf_dl_jrb_textures_0A000_rgba16_ci8_pal_rgba16[];
extern u8 wf_dl_rr_textures_01000_rgba16_ci8[];
extern u8 wf_dl_rr_textures_01000_rgba16_ci8_pal_rgba16[];
extern u8 wf_dl_ccm_textures_00000_rgba16_ci8[];
extern u8 wf_dl_ccm_textures_00000_rgba16_ci8_pal_rgba16[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[364];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_1[372];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_2[44];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_3[475];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Plane_001_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_001_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_grass[];
extern Gfx mat_revert_wf_dl_grass[];
extern Gfx mat_wf_dl_dirt[];
extern Gfx mat_revert_wf_dl_dirt[];
extern Gfx mat_wf_dl_wood[];
extern Gfx mat_revert_wf_dl_wood[];
extern Gfx mat_wf_dl_cobblestone[];
extern Gfx mat_revert_wf_dl_cobblestone[];
extern Gfx mat_wf_dl_bridge[];
extern Gfx mat_revert_wf_dl_bridge[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_Plane_001_mesh_layer_5[];
extern Gfx wf_dl_material_revert_render_settings[];
